import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin:
https://github.com/gfxholo/iconic
*/
`;

const prod = (process.argv[2] === 'production');

const manifestPath = './manifest.json';
const manifestStr = fs.readFileSync(manifestPath, 'utf8');
const manifest = JSON.parse(manifestStr);
const releaseDir = prod ? `./release/v${manifest.version}` : '.';

if (prod && !fs.existsSync(releaseDir)) {
	fs.mkdirSync(releaseDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/IconicPlugin.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(releaseDir, 'main.js'),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	
	// Copy extra files
	fs.copyFileSync(manifestPath, path.join(releaseDir, 'manifest.json'));
	if (fs.existsSync('./styles.css')) {
		fs.copyFileSync('./styles.css', path.join(releaseDir, 'styles.css'));
	}
	console.log(`\n🎉 Build complete! Release files are located in '${releaseDir}'`);
	
	process.exit(0);
} else {
	await context.watch();
}